/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JList; 

/**
 *
 * @author Anton
 */
public class MenuMall extends javax.swing.JFrame {

    /**
     * Creates new form MenuMall
     */
    public MenuMall() {
        initComponents();
        scheduleButton.doClick();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffFormPopup = new javax.swing.JDialog();
        newStaffPane = new javax.swing.JPanel();
        saveStaffButton = new javax.swing.JButton();
        staffNameField = new javax.swing.JTextField();
        activeCheck = new javax.swing.JCheckBox();
        staffAccountBox = new javax.swing.JComboBox();
        staffDeptBox = new javax.swing.JComboBox();
        accountTypeLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        staffPhoneField = new javax.swing.JFormattedTextField();
        wrongInfoLabel2 = new javax.swing.JLabel();
        activityFormPopup = new javax.swing.JDialog();
        newActivityPane = new javax.swing.JPanel();
        notesField = new java.awt.TextArea();
        timeField = new javax.swing.JFormattedTextField();
        nameField = new javax.swing.JTextField();
        participantsField = new javax.swing.JTextField();
        saveActivityButton = new javax.swing.JButton();
        dateField = new javax.swing.JFormattedTextField();
        wrongInfoLabel = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        titlePane = new javax.swing.JPanel();
        windowTitle = new javax.swing.JLabel();
        currentTab = new javax.swing.JLabel();
        basePane = new javax.swing.JPanel();
        upperResultPane = new javax.swing.JPanel();
        resultPane = new javax.swing.JScrollPane();
        buttonMenuPane = new javax.swing.JPanel();
        scheduleButton = new javax.swing.JButton();
        activityButton = new javax.swing.JButton();
        workShiftButton = new javax.swing.JButton();
        careButton = new javax.swing.JButton();
        staffRegButton = new javax.swing.JButton();
        resRegButton = new javax.swing.JButton();
        deptScheduleButton = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        showButtonsButton = new javax.swing.JButton();
        hideButtonsButton = new javax.swing.JButton();
        bottomPane = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        newStaffButton = new javax.swing.JButton();
        newActivityButton = new javax.swing.JButton();

        staffFormPopup.setSize(362,200);
        staffFormPopup.setLocationRelativeTo(null);
        staffFormPopup.setMinimumSize(new java.awt.Dimension(290, 164));
        activityFormPopup.setAlwaysOnTop(true);
        staffFormPopup.setResizable(false);

        newStaffPane.setMaximumSize(new java.awt.Dimension(290, 164));
        newStaffPane.setPreferredSize(new java.awt.Dimension(290, 164));

        saveStaffButton.setText("Registrera ");
        saveStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStaffButtonActionPerformed(evt);
            }
        });

        staffNameField.setText("Namn");
        staffNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffNameFieldActionPerformed(evt);
            }
        });

        activeCheck.setSelected(true);
        activeCheck.setText("Aktiv");
        activeCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeCheckActionPerformed(evt);
            }
        });

        staffAccountBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Personal", "Sjuksköterska", "Chef"}));

        staffDeptBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Balders hage"}));
        staffDeptBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffDeptBoxActionPerformed(evt);
            }
        });

        accountTypeLabel.setText("Kontotyp:");

        deptLabel.setText("Avdelning:");

        staffPhoneField.setText("Telefonnummer");
        staffPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffPhoneFieldActionPerformed(evt);
            }
        });

        wrongInfoLabel2.setVisible(false);
        wrongInfoLabel2.setForeground(new java.awt.Color(255, 0, 0));
        wrongInfoLabel2.setText("Alla fält skall vara ifyllda!");

        javax.swing.GroupLayout newStaffPaneLayout = new javax.swing.GroupLayout(newStaffPane);
        newStaffPane.setLayout(newStaffPaneLayout);
        newStaffPaneLayout.setHorizontalGroup(
            newStaffPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStaffPaneLayout.createSequentialGroup()
                .addGroup(newStaffPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newStaffPaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(staffNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(accountTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staffAccountBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newStaffPaneLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(saveStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newStaffPaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(newStaffPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newStaffPaneLayout.createSequentialGroup()
                                .addComponent(activeCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(wrongInfoLabel2))
                            .addGroup(newStaffPaneLayout.createSequentialGroup()
                                .addComponent(staffPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staffDeptBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newStaffPaneLayout.setVerticalGroup(
            newStaffPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStaffPaneLayout.createSequentialGroup()
                .addGroup(newStaffPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newStaffPaneLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(newStaffPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staffAccountBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newStaffPaneLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(accountTypeLabel)))
                .addGroup(newStaffPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newStaffPaneLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(newStaffPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staffDeptBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newStaffPaneLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(deptLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newStaffPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activeCheck)
                    .addComponent(wrongInfoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout staffFormPopupLayout = new javax.swing.GroupLayout(staffFormPopup.getContentPane());
        staffFormPopup.getContentPane().setLayout(staffFormPopupLayout);
        staffFormPopupLayout.setHorizontalGroup(
            staffFormPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newStaffPane, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        staffFormPopupLayout.setVerticalGroup(
            staffFormPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newStaffPane, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );

        activityFormPopup.setTitle("Skapa ny användare");
        activityFormPopup.setAlwaysOnTop(true);
        activityFormPopup.setBounds(new java.awt.Rectangle(0, 0, 290, 270));
        activityFormPopup.setMaximumSize(new java.awt.Dimension(290, 300));
        activityFormPopup.setMinimumSize(new java.awt.Dimension(290, 300));
        activityFormPopup.setResizable(false);

        newActivityPane.setMaximumSize(new java.awt.Dimension(290, 272));
        newActivityPane.setMinimumSize(new java.awt.Dimension(290, 272));

        notesField.setColumns(10);
        notesField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        timeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        timeField.setText("Tid");
        timeField.setToolTipText("Använd formatet hh:mm");
        timeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFieldActionPerformed(evt);
            }
        });

        nameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameField.setText("Aktivitetsnamn");
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        participantsField.setText("Deltagare");
        participantsField.setToolTipText("Separera deltagare med kommatecken");

        saveActivityButton.setText("Spara ny aktivitet");
        saveActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActivityButtonActionPerformed(evt);
            }
        });

        dateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        dateField.setText("Datum");
        dateField.setToolTipText("Använd formatet åååå-mm-dd");
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });

        wrongInfoLabel.setForeground(new java.awt.Color(255, 0, 0));
        wrongInfoLabel.setText("Alla fält skall vara ifyllda!");

        javax.swing.GroupLayout newActivityPaneLayout = new javax.swing.GroupLayout(newActivityPane);
        newActivityPane.setLayout(newActivityPaneLayout);
        newActivityPaneLayout.setHorizontalGroup(
            newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newActivityPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newActivityPaneLayout.createSequentialGroup()
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dateField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newActivityPaneLayout.createSequentialGroup()
                            .addComponent(participantsField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(timeField))
                        .addGroup(newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notesField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(wrongInfoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newActivityPaneLayout.setVerticalGroup(
            newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newActivityPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(participantsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(notesField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrongInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout activityFormPopupLayout = new javax.swing.GroupLayout(activityFormPopup.getContentPane());
        activityFormPopup.getContentPane().setLayout(activityFormPopupLayout);
        activityFormPopupLayout.setHorizontalGroup(
            activityFormPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newActivityPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        activityFormPopupLayout.setVerticalGroup(
            activityFormPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newActivityPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InfoSys");
        setResizable(false);

        windowTitle.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        windowTitle.setText("Baldurs Hage:");

        currentTab.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        currentTab.setText("Arbetsschema");

        javax.swing.GroupLayout titlePaneLayout = new javax.swing.GroupLayout(titlePane);
        titlePane.setLayout(titlePaneLayout);
        titlePaneLayout.setHorizontalGroup(
            titlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePaneLayout.createSequentialGroup()
                .addComponent(windowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(currentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titlePaneLayout.setVerticalGroup(
            titlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(currentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        upperResultPane.setForeground(new java.awt.Color(51, 51, 255));
        upperResultPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        resultPane.setForeground(new java.awt.Color(255, 51, 0));
        resultPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        resultPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout upperResultPaneLayout = new javax.swing.GroupLayout(upperResultPane);
        upperResultPane.setLayout(upperResultPaneLayout);
        upperResultPaneLayout.setHorizontalGroup(
            upperResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultPane, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        upperResultPaneLayout.setVerticalGroup(
            upperResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperResultPaneLayout.createSequentialGroup()
                .addComponent(resultPane, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        scheduleButton.setText("Arbetsschema");
        scheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleButtonActionPerformed(evt);
            }
        });

        activityButton.setText("Aktiviteter");
        activityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activityButtonActionPerformed(evt);
            }
        });

        workShiftButton.setText("Arbetspassplan");
        workShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workShiftButtonActionPerformed(evt);
            }
        });

        careButton.setText("Omsorgsåtgärder");
        careButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                careButtonActionPerformed(evt);
            }
        });

        staffRegButton.setText("Personalregister");
        staffRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffRegButtonActionPerformed(evt);
            }
        });

        resRegButton.setText("Boenderegister");
        resRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resRegButtonActionPerformed(evt);
            }
        });

        deptScheduleButton.setText("Avdelningsplan");
        deptScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptScheduleButtonActionPerformed(evt);
            }
        });

        logOut.setText("Logga ut");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        showButtonsButton.setText("Visa");
        showButtonsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonsButtonActionPerformed(evt);
            }
        });

        hideButtonsButton.setText("Dölj");
        hideButtonsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideButtonsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonMenuPaneLayout = new javax.swing.GroupLayout(buttonMenuPane);
        buttonMenuPane.setLayout(buttonMenuPaneLayout);
        buttonMenuPaneLayout.setHorizontalGroup(
            buttonMenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonMenuPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(showButtonsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hideButtonsButton)
                .addGap(20, 20, 20))
            .addGroup(buttonMenuPaneLayout.createSequentialGroup()
                .addGroup(buttonMenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workShiftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(careButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        buttonMenuPaneLayout.setVerticalGroup(
            buttonMenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonMenuPaneLayout.createSequentialGroup()
                .addComponent(activityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(staffRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buttonMenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showButtonsButton)
                    .addComponent(hideButtonsButton))
                .addGap(10, 10, 10)
                .addComponent(scheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deptScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workShiftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(careButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        searchButton.setText("Sök");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchField.setText("Skriv in ID...");

        newStaffButton.setText("Registrera ny personal");
        newStaffButton.setToolTipText("");
        newStaffButton.setAlignmentX(0.5F);
        newStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStaffButtonActionPerformed(evt);
            }
        });

        newActivityButton.setText("Skapa ny");
        newActivityButton.setToolTipText("");
        newActivityButton.setOpaque(false);
        newActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newActivityButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPaneLayout = new javax.swing.GroupLayout(bottomPane);
        bottomPane.setLayout(bottomPaneLayout);
        bottomPaneLayout.setHorizontalGroup(
            bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(newActivityButton)
                .addGap(6, 6, 6)
                .addComponent(newStaffButton)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        bottomPaneLayout.setVerticalGroup(
            bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout basePaneLayout = new javax.swing.GroupLayout(basePane);
        basePane.setLayout(basePaneLayout);
        basePaneLayout.setHorizontalGroup(
            basePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePaneLayout.createSequentialGroup()
                .addComponent(buttonMenuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(basePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(upperResultPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottomPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        basePaneLayout.setVerticalGroup(
            basePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePaneLayout.createSequentialGroup()
                .addGroup(basePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bottomPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(upperResultPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonMenuPane, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );

        newActivityPane.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(basePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basePane, javax.swing.GroupLayout.PREFERRED_SIZE, 375, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void activityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activityButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(true);
        newStaffButton.setVisible(false);
        currentTab.setText("Aktiviteter");
    }//GEN-LAST:event_activityButtonActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        this.setVisible(false);
        MenuLogin.main(arr);
    }//GEN-LAST:event_logOutActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void formButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        newStaffPane.setVisible(false);
        activityFormPopup.setVisible(true);
        newActivityPane.setVisible(true);
    }      
    
    private void scheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(false);
        currentTab.setText("Arbetsschema");
    }//GEN-LAST:event_scheduleButtonActionPerformed

    private void workShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workShiftButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(false);
        currentTab.setText("Arbetspassplan");
    }//GEN-LAST:event_workShiftButtonActionPerformed

    private void careButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_careButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(false);
        currentTab.setText("Omsorgsåtgärder");
    }//GEN-LAST:event_careButtonActionPerformed

    private void staffRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffRegButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(true);
        currentTab.setText("Personalregister");
    }//GEN-LAST:event_staffRegButtonActionPerformed

    private void resRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resRegButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(false);
        currentTab.setText("Boenderegister");
    }//GEN-LAST:event_resRegButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void timeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeFieldActionPerformed

    private void saveActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActivityButtonActionPerformed
        String name, date, time, notes, participants;
        name = nameField.getText();
        date = dateField.getText();
        time = timeField.getText();
        notes = notesField.getText();
        participants = participantsField.getText();
        
        if(name.equals("") || participants.equals("") || time.equals("") || date.equals("")){
            wrongInfoLabel.setVisible(true);
            activityFormPopup.pack();
        }else{
            System.out.println("Före addActivity");
            dbh.addActivity(name, time, date, notes);
            System.out.println("efter addActivity");
            String activityID = dbh.getActivityID(name, time, date);
            ArrayList<String> participantsArr = new ArrayList(
                Arrays.asList(participants.split(", ")));
            for(String s : participantsArr){
                dbh.addParticipants(s, activityID);
                System.out.println("inuti participants for-loop");
            }
 
              
            resultPane.setVisible(true);
            activityFormPopup.setVisible(false);
        }
        
        

        //formButton.setVisible(false);
    }//GEN-LAST:event_saveActivityButtonActionPerformed

    private void deptScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptScheduleButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(false);
        currentTab.setText("Avdelningsplan");
    }//GEN-LAST:event_deptScheduleButtonActionPerformed

    private void staffNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffNameFieldActionPerformed

    private void activeCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeCheckActionPerformed

    private void staffPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffPhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffPhoneFieldActionPerformed

    private void saveStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStaffButtonActionPerformed
        String name, phone, department, accountType;
        boolean active;
        name = staffNameField.getText();
        phone = staffPhoneField.getText();
        department = (String) staffDeptBox.getSelectedItem();
        accountType = (String) staffAccountBox.getSelectedItem();
       
        if(name.equals("") || phone.equals("") || department.equals("") || accountType.equals("")){
            wrongInfoLabel2.setVisible(true);
            staffFormPopup.pack();
        }else{
            resultPane.setVisible(true);
            staffFormPopup.setVisible(false);
            //funktionsanrop
        }
    }//GEN-LAST:event_saveStaffButtonActionPerformed

    private void newStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStaffButtonActionPerformed
        staffFormPopup.pack();
        staffFormPopup.setVisible(true);
    }//GEN-LAST:event_newStaffButtonActionPerformed
//GEN-FIRST:event_formButtonActionPerformed
 
//GEN-LAST:event_formButtonActionPerformed

    private void newActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newActivityButtonActionPerformed
        activityFormPopup.pack();
        activityFormPopup.setLocationRelativeTo(null);
        activityFormPopup.setVisible(true);
        newActivityPane.setVisible(true);
        wrongInfoLabel.setVisible(false);
        //notesField.setLineWrap(false);

    }//GEN-LAST:event_newActivityButtonActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void staffDeptBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffDeptBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffDeptBoxActionPerformed

    private void hideButtonsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideButtonsButtonActionPerformed
        scheduleButton.setVisible(false);
        workShiftButton.setVisible(false);
        resRegButton.setVisible(false);
        deptScheduleButton.setVisible(false);
        careButton.setVisible(false);
        this.pack();
    }//GEN-LAST:event_hideButtonsButtonActionPerformed

    private void showButtonsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonsButtonActionPerformed
        scheduleButton.setVisible(true);
        workShiftButton.setVisible(true);
        resRegButton.setVisible(true);
        deptScheduleButton.setVisible(true);
        careButton.setVisible(true);
        this.pack();
        
    }//GEN-LAST:event_showButtonsButtonActionPerformed
    
    public static void printResult(ArrayList<String> listData){
	JList<String> list = new JList(listData.toArray());
	resultPane.removeAll();
        resultPane.add(list);
	resultPane.updateUI();
    }
  /**  public void centerOnParent(final Window child, final boolean absolute) {
        child.pack();
        boolean useChildsOwner = child.getOwner() != null ? ((child.getOwner() instanceof JFrame) || (child.getOwner() instanceof JDialog)) : false;
        final Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        final Dimension parentSize = useChildsOwner ? child.getOwner().getSize() : screenSize ;
        final Point parentLocationOnScreen = useChildsOwner ? child.getOwner().getLocationOnScreen() : new Point(0,0) ;
        final Dimension childSize = child.getSize();
        childSize.width = Math.min(childSize.width, screenSize.width);
        childSize.height = Math.min(childSize.height, screenSize.height);
        child.setSize(childSize);        
        int x;
        int y;
        if ((child.getOwner() != null) && child.getOwner().isShowing()) {
            x = (parentSize.width - childSize.width) / 2;
            y = (parentSize.height - childSize.height) / 2;
            x += parentLocationOnScreen.x;
            y += parentLocationOnScreen.y;
        } else {
            x = (screenSize.width - childSize.width) / 2;
            y = (screenSize.height - childSize.height) / 2;
        }
        if (!absolute) {
            x /= 2;
            y /= 2;
        }
        child.setLocation(x, y);
    }*/
    
    String [] arr;
    static DatabaseHandler dbh = new DatabaseHandler();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JCheckBox activeCheck;
    private javax.swing.JButton activityButton;
    private javax.swing.JDialog activityFormPopup;
    private javax.swing.JPanel basePane;
    private javax.swing.JPanel bottomPane;
    private javax.swing.JPanel buttonMenuPane;
    private javax.swing.JButton careButton;
    private javax.swing.JLabel currentTab;
    private javax.swing.JFormattedTextField dateField;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JButton deptScheduleButton;
    private javax.swing.JButton hideButtonsButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton newActivityButton;
    private javax.swing.JPanel newActivityPane;
    private javax.swing.JButton newStaffButton;
    private javax.swing.JPanel newStaffPane;
    private java.awt.TextArea notesField;
    private javax.swing.JTextField participantsField;
    private javax.swing.JButton resRegButton;
    private static javax.swing.JScrollPane resultPane;
    private javax.swing.JButton saveActivityButton;
    private javax.swing.JButton saveStaffButton;
    private javax.swing.JButton scheduleButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton showButtonsButton;
    private javax.swing.JComboBox staffAccountBox;
    private javax.swing.JComboBox staffDeptBox;
    private javax.swing.JDialog staffFormPopup;
    private javax.swing.JTextField staffNameField;
    private javax.swing.JFormattedTextField staffPhoneField;
    private javax.swing.JButton staffRegButton;
    private javax.swing.JFormattedTextField timeField;
    private javax.swing.JPanel titlePane;
    private javax.swing.JPanel upperResultPane;
    private javax.swing.JLabel windowTitle;
    private javax.swing.JButton workShiftButton;
    private javax.swing.JLabel wrongInfoLabel;
    private javax.swing.JLabel wrongInfoLabel2;
    // End of variables declaration//GEN-END:variables
}
