/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//import java.awt.Toolkit;

/**
 *
 * @author Anton
 */
public class MenuMall extends javax.swing.JFrame {

    /**
     * Creates new form MenuMall
     */
    public MenuMall() {
        initComponents();
        scheduleButton.doClick();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffFormPopup = new javax.swing.JDialog();
        newStaffPane = new javax.swing.JPanel();
        saveStaffButton = new javax.swing.JButton();
        staffNameField = new javax.swing.JTextField();
        activeCheck = new javax.swing.JCheckBox();
        staffAccountBox = new javax.swing.JComboBox();
        staffDeptBox = new javax.swing.JComboBox();
        accountTypeLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        staffPhoneField = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        activityFormPopup = new javax.swing.JDialog();
        newActivityPane = new javax.swing.JPanel();
        notesField = new java.awt.TextArea();
        timeField = new javax.swing.JFormattedTextField();
        nameField = new javax.swing.JTextField();
        participantsField = new javax.swing.JTextField();
        saveActivityButton = new javax.swing.JButton();
        dateField = new javax.swing.JFormattedTextField();
        wrongInfoLabel = new javax.swing.JLabel();
        titlePane = new javax.swing.JPanel();
        windowTitle = new javax.swing.JLabel();
        currentTab = new javax.swing.JLabel();
        basePane = new javax.swing.JPanel();
        upperResultPane = new javax.swing.JPanel();
        resultPane = new javax.swing.JScrollPane();
        buttonMenuPane = new javax.swing.JPanel();
        scheduleButton = new javax.swing.JButton();
        activityButton = new javax.swing.JButton();
        workShiftButton = new javax.swing.JButton();
        careButton = new javax.swing.JButton();
        staffRegButton = new javax.swing.JButton();
        resRegButton = new javax.swing.JButton();
        deptScheduleButton = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        bottomPane = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        newStaffButton = new javax.swing.JButton();
        newActivityButton = new javax.swing.JButton();

        staffFormPopup.setSize(362,200);
        staffFormPopup.setLocationRelativeTo(null);
        staffFormPopup.setMaximumSize(new java.awt.Dimension(290, 261));
        staffFormPopup.setMinimumSize(new java.awt.Dimension(290, 164));
        activityFormPopup.setAlwaysOnTop(true);
        staffFormPopup.setPreferredSize(new java.awt.Dimension(362, 200));
        staffFormPopup.setResizable(false);

        newStaffPane.setMaximumSize(new java.awt.Dimension(290, 164));
        newStaffPane.setPreferredSize(new java.awt.Dimension(290, 164));
        newStaffPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveStaffButton.setText("Registrera ");
        saveStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStaffButtonActionPerformed(evt);
            }
        });
        newStaffPane.add(saveStaffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 238, 40));

        staffNameField.setText("Namn");
        staffNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffNameFieldActionPerformed(evt);
            }
        });
        newStaffPane.add(staffNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 148, -1));

        activeCheck.setText("Aktiv");
        activeCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeCheckActionPerformed(evt);
            }
        });
        newStaffPane.add(activeCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 78, -1));

        staffAccountBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Personal", "Sjuksköterska", "Chef"}));
        newStaffPane.add(staffAccountBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 11, 120, -1));

        staffDeptBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Balders hage"}));
        newStaffPane.add(staffDeptBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 42, 120, -1));

        accountTypeLabel.setText("Kontotyp:");
        newStaffPane.add(accountTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 14, -1, -1));

        deptLabel.setText("Avdelning:");
        newStaffPane.add(deptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 45, -1, -1));

        staffPhoneField.setText("Telefonnummer");
        staffPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffPhoneFieldActionPerformed(evt);
            }
        });
        newStaffPane.add(staffPhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 148, -1));

        jLabel1.setText("jLabel1");
        newStaffPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        javax.swing.GroupLayout staffFormPopupLayout = new javax.swing.GroupLayout(staffFormPopup.getContentPane());
        staffFormPopup.getContentPane().setLayout(staffFormPopupLayout);
        staffFormPopupLayout.setHorizontalGroup(
            staffFormPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newStaffPane, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        staffFormPopupLayout.setVerticalGroup(
            staffFormPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newStaffPane, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        activityFormPopup.setTitle("Skapa ny användare");
        activityFormPopup.setAlwaysOnTop(true);
        activityFormPopup.setBounds(new java.awt.Rectangle(0, 0, 290, 270));
        activityFormPopup.setMaximumSize(new java.awt.Dimension(290, 300));
        activityFormPopup.setMinimumSize(new java.awt.Dimension(290, 300));
        activityFormPopup.setResizable(false);
        activityFormPopup.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newActivityPane.setMaximumSize(new java.awt.Dimension(290, 272));
        newActivityPane.setMinimumSize(new java.awt.Dimension(290, 272));

        notesField.setColumns(10);
        notesField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        timeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        timeField.setText("Tid");
        timeField.setToolTipText("Använd formatet hh:mm");
        timeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFieldActionPerformed(evt);
            }
        });

        nameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameField.setText("Aktivitetsnamn");
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        participantsField.setText("Deltagare");
        participantsField.setToolTipText("Separera deltagare med kommatecken");

        saveActivityButton.setText("Spara ny aktivitet");
        saveActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActivityButtonActionPerformed(evt);
            }
        });

        dateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        dateField.setText("Datum");
        dateField.setToolTipText("Använd formatet dd-mm-yyyy");

        wrongInfoLabel.setForeground(new java.awt.Color(255, 0, 0));
        wrongInfoLabel.setText("Alla fält skall vara ifyllda!");

        javax.swing.GroupLayout newActivityPaneLayout = new javax.swing.GroupLayout(newActivityPane);
        newActivityPane.setLayout(newActivityPaneLayout);
        newActivityPaneLayout.setHorizontalGroup(
            newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newActivityPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newActivityPaneLayout.createSequentialGroup()
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dateField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newActivityPaneLayout.createSequentialGroup()
                            .addComponent(participantsField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(timeField))
                        .addGroup(newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notesField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(wrongInfoLabel))
                .addGap(592, 592, 592))
        );
        newActivityPaneLayout.setVerticalGroup(
            newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newActivityPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(newActivityPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(participantsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(notesField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrongInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        activityFormPopup.getContentPane().add(newActivityPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InfoSys");
        setResizable(false);

        windowTitle.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        windowTitle.setText("Baldurs Hage:");

        currentTab.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        currentTab.setText("Arbetsschema");

        javax.swing.GroupLayout titlePaneLayout = new javax.swing.GroupLayout(titlePane);
        titlePane.setLayout(titlePaneLayout);
        titlePaneLayout.setHorizontalGroup(
            titlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePaneLayout.createSequentialGroup()
                .addComponent(windowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        titlePaneLayout.setVerticalGroup(
            titlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePaneLayout.createSequentialGroup()
                .addGroup(titlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(windowTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(currentTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        basePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upperResultPane.setForeground(new java.awt.Color(51, 51, 255));
        upperResultPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        resultPane.setForeground(new java.awt.Color(255, 51, 0));
        resultPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        resultPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout upperResultPaneLayout = new javax.swing.GroupLayout(upperResultPane);
        upperResultPane.setLayout(upperResultPaneLayout);
        upperResultPaneLayout.setHorizontalGroup(
            upperResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultPane, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        upperResultPaneLayout.setVerticalGroup(
            upperResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultPane, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        basePane.add(upperResultPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 550, 270));
        newActivityPane.setVisible(false);

        buttonMenuPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scheduleButton.setText("Arbetsschema");
        scheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleButtonActionPerformed(evt);
            }
        });
        buttonMenuPane.add(scheduleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        activityButton.setText("Aktiviteter");
        activityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activityButtonActionPerformed(evt);
            }
        });
        buttonMenuPane.add(activityButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 30));

        workShiftButton.setText("Arbetspassplan");
        workShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workShiftButtonActionPerformed(evt);
            }
        });
        buttonMenuPane.add(workShiftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 30));

        careButton.setText("Omsorgsåtgärder");
        careButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                careButtonActionPerformed(evt);
            }
        });
        buttonMenuPane.add(careButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 30));

        staffRegButton.setText("Personalregister");
        staffRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffRegButtonActionPerformed(evt);
            }
        });
        buttonMenuPane.add(staffRegButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, 30));

        resRegButton.setText("Boenderegister");
        resRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resRegButtonActionPerformed(evt);
            }
        });
        buttonMenuPane.add(resRegButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 180, 30));

        deptScheduleButton.setText("Avdelningsplan");
        deptScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptScheduleButtonActionPerformed(evt);
            }
        });
        buttonMenuPane.add(deptScheduleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 30));

        logOut.setText("Logga ut");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        buttonMenuPane.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 180, 80));

        basePane.add(buttonMenuPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 350));

        bottomPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchButton.setText("Sök");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchField.setText("Skriv in ID...");

        newStaffButton.setText("Registrera ny personal");
        newStaffButton.setToolTipText("");
        newStaffButton.setAlignmentX(0.5F);
        newStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStaffButtonActionPerformed(evt);
            }
        });

        newActivityButton.setText("Skapa ny");
        newActivityButton.setToolTipText("");
        newActivityButton.setOpaque(false);
        newActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newActivityButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPaneLayout = new javax.swing.GroupLayout(bottomPane);
        bottomPane.setLayout(bottomPaneLayout);
        bottomPaneLayout.setHorizontalGroup(
            bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newActivityButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newStaffButton)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        bottomPaneLayout.setVerticalGroup(
            bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        basePane.add(bottomPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 550, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titlePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basePane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void activityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activityButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(true);
        newStaffButton.setVisible(false);
        currentTab.setText("Aktiviteter");
    }//GEN-LAST:event_activityButtonActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        this.setVisible(false);
        MenuLogin.main(arr);
    }//GEN-LAST:event_logOutActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void formButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        newStaffPane.setVisible(false);
        activityFormPopup.setVisible(true);
        newActivityPane.setVisible(true);
    }      
    
    private void scheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(false);
        currentTab.setText("Arbetsschema");
    }//GEN-LAST:event_scheduleButtonActionPerformed

    private void workShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workShiftButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(false);
        currentTab.setText("Arbetspassplan");
    }//GEN-LAST:event_workShiftButtonActionPerformed

    private void careButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_careButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(false);
        currentTab.setText("Omsorgsåtgärder");
    }//GEN-LAST:event_careButtonActionPerformed

    private void staffRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffRegButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(true);
        currentTab.setText("Personalregister");
    }//GEN-LAST:event_staffRegButtonActionPerformed

    private void resRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resRegButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(false);
        currentTab.setText("Boenderegister");
    }//GEN-LAST:event_resRegButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void timeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeFieldActionPerformed

    private void saveActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActivityButtonActionPerformed
        if(nameField.getText() == null || dateField.getText() == null || 
           participantsField.getText() == null || timeField.getText() == null){
            wrongInfoLabel.setVisible(true);
        }
        
        resultPane.setVisible(true);
        activityFormPopup.setVisible(false);

        //formButton.setVisible(false);
    }//GEN-LAST:event_saveActivityButtonActionPerformed

    private void deptScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptScheduleButtonActionPerformed
        resultPane.setVisible(true);
        newActivityButton.setVisible(false);
        newStaffButton.setVisible(false);
        currentTab.setText("Avdelningsplan");
    }//GEN-LAST:event_deptScheduleButtonActionPerformed

    private void staffNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffNameFieldActionPerformed

    private void activeCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeCheckActionPerformed

    private void staffPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffPhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffPhoneFieldActionPerformed

    private void saveStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStaffButtonActionPerformed
        resultPane.setVisible(true);
        staffFormPopup.setVisible(false);
    }//GEN-LAST:event_saveStaffButtonActionPerformed

    private void newStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStaffButtonActionPerformed
        staffFormPopup.pack();
        staffFormPopup.setVisible(true);
    }//GEN-LAST:event_newStaffButtonActionPerformed
//GEN-FIRST:event_formButtonActionPerformed
 
//GEN-LAST:event_formButtonActionPerformed

    private void newActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newActivityButtonActionPerformed
        activityFormPopup.pack();
        activityFormPopup.setLocationRelativeTo(null);
        activityFormPopup.setVisible(true);
        newActivityPane.setVisible(true);
        wrongInfoLabel.setVisible(false);
        //notesField.setLineWrap(false);

    }//GEN-LAST:event_newActivityButtonActionPerformed

  /**  public void centerOnParent(final Window child, final boolean absolute) {
        child.pack();
        boolean useChildsOwner = child.getOwner() != null ? ((child.getOwner() instanceof JFrame) || (child.getOwner() instanceof JDialog)) : false;
        final Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        final Dimension parentSize = useChildsOwner ? child.getOwner().getSize() : screenSize ;
        final Point parentLocationOnScreen = useChildsOwner ? child.getOwner().getLocationOnScreen() : new Point(0,0) ;
        final Dimension childSize = child.getSize();
        childSize.width = Math.min(childSize.width, screenSize.width);
        childSize.height = Math.min(childSize.height, screenSize.height);
        child.setSize(childSize);        
        int x;
        int y;
        if ((child.getOwner() != null) && child.getOwner().isShowing()) {
            x = (parentSize.width - childSize.width) / 2;
            y = (parentSize.height - childSize.height) / 2;
            x += parentLocationOnScreen.x;
            y += parentLocationOnScreen.y;
        } else {
            x = (screenSize.width - childSize.width) / 2;
            y = (screenSize.height - childSize.height) / 2;
        }
        if (!absolute) {
            x /= 2;
            y /= 2;
        }
        child.setLocation(x, y);
    }*/
    
   String [] arr;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JCheckBox activeCheck;
    private javax.swing.JButton activityButton;
    private javax.swing.JDialog activityFormPopup;
    private javax.swing.JPanel basePane;
    private javax.swing.JPanel bottomPane;
    private javax.swing.JPanel buttonMenuPane;
    private javax.swing.JButton careButton;
    private javax.swing.JLabel currentTab;
    private javax.swing.JFormattedTextField dateField;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JButton deptScheduleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton newActivityButton;
    private javax.swing.JPanel newActivityPane;
    private javax.swing.JButton newStaffButton;
    private javax.swing.JPanel newStaffPane;
    private java.awt.TextArea notesField;
    private javax.swing.JTextField participantsField;
    private javax.swing.JButton resRegButton;
    private javax.swing.JScrollPane resultPane;
    private javax.swing.JButton saveActivityButton;
    private javax.swing.JButton saveStaffButton;
    private javax.swing.JButton scheduleButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox staffAccountBox;
    private javax.swing.JComboBox staffDeptBox;
    private javax.swing.JDialog staffFormPopup;
    private javax.swing.JTextField staffNameField;
    private javax.swing.JFormattedTextField staffPhoneField;
    private javax.swing.JButton staffRegButton;
    private javax.swing.JFormattedTextField timeField;
    private javax.swing.JPanel titlePane;
    private javax.swing.JPanel upperResultPane;
    private javax.swing.JLabel windowTitle;
    private javax.swing.JButton workShiftButton;
    private javax.swing.JLabel wrongInfoLabel;
    // End of variables declaration//GEN-END:variables
}
